#MARIAH SQLIT3 TO POSTGRES

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development: 
  <<: *default
  database: popac_development
  
test: 
  <<: *default
  database: popac_test
  
production: 
  <<: *default  

